Intros and outros
SlimeCubed/SlugBaseRemix pull request #13
Opened 2023-07-14 03:39 UTC by Moon613

2023-07-14 03:55 UTC, Moon613 commented
Meant to send this to my own main before making a PR so I could be sure that it was all cleaned up properly, but I goofed ¯\_(ツ)_/¯. It should be good now anyway, probably.

2023-07-16 08:14 UTC, SlimeCubed requested changes
Thanks for your contribution! I wasn't looking forward to making this bit, so I'm glad someone else got to it before me :)

Most of it looks good, but there are a few things that I do think should be changed. In general, the slideshow system currently has too many special cases where it only works if the slideshow is an intro or outro. Leave a comment here if you need any help/info/whatever, but I'll probably see messages sooner on Discord.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/AssetHooks.cs
> +                    if (IntroScene.TryGet(chara, out var newIntroSlideShowID) && slideShowID == newIntroSlideShowID && CustomSlideshow.Registry.TryGet(newIntroSlideShowID, out var customIntroSlidesho
`CustomSlideshow.Registry` should be the only thing that matters here. Even if the slugcat that owns the slideshow isn't currently selected, the slideshow should ideally still work. This current code will also not respect any slideshows that are added to the registry directly unless they're also added to an "intro_scene" or "outro_scenes" feature.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/AssetHooks.cs
> +                if (IntroScene.TryGet(chara, out var newIntroSlideShowID) && self.menu is SlideShow slideShow && slideShow.slideShowID == newIntroSlideShowID && CustomSlideshow.Registry.TryGet(newInt
As with `SlideShow_ctor`, this should forgo checking any of the slugcat-specific features and only check the slideshow registry.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/AssetHooks.cs
> +                if (IntroScene.TryGet(chara, out var newIntroSlideShowID) && self.menu is SlideShow slideShow && slideShow.slideShowID == newIntroSlideShowID && CustomSlideshow.Registry.TryGet(newInt
As with `SlideShow_ctor`, this should forgo checking any of the slugcat-specific features and only check the slideshow registry.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/AssetHooks.cs
> +                CustomScene.QueueDream("");
Try not to add side-effects to methods that didn't previously have them. I recommend reworking the dream system to not rely on static variables.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/AssetHooks.cs
> +            if (intro) { self.processAfterSlideShow = ProcessManager.ProcessID.Game; }
Would it be better if the slideshow JSON took "next_process" instead of "to_credits"? I'm not sure.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/AssetHooks.cs
> +                if (new SceneID($"Slugbase_{charaName}_{customSlideshow.ID}_{scene.Name}_intro", false) == sceneID && !self.flatMode)
Consider adding a method, `CustomSlideshow.GetScene(string name)`, that does this search for you. Storing a `Dictionary<string, Scene>` would make it more convenient and skip a bunch of string interpolation.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/CustomScene.cs
> +        public static void QueueDream(string name)
This should be reworked to not depend on static variables. In its current state, it's rather fragile. Consider having the modder pass in a `DreamsState`, then either store the queued dream with a CWT or somehow use the existing `eventDream` system. This should make the dream leaking between save states impossible

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/CustomScene.cs
> +        public static string nextDreamID { get; private set; } = "";
This should be capitalized since it's a property.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/CustomSlideshow.cs
> +        public class Scene
I don't like how much of this is copy-pasted from `CustomScene`. You should remove the duplicate properties, then either make this class inherit from `CustomScene` or add a property that stores a `CustomScene`.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/CustomSlideshow.cs
> +        public class MMusic{
Maybe call this `SlideshowMusic` instead of `MMusic`? I'd rather be a little redundant than have people wonder what the "M" stands for.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/CustomSlideshow.cs
> +            // Don't know if I should force it to defalut to the normal intro theme or leave it empty so that it's an option for people to not have any music (But who would choose that? Someone proba
I'd rather it default to silence. The slideshow system should be fairly flexible, so who knows what people will use it for. Maybe they want to handle the music logic themselves!

2023-07-16 08:14 UTC, SlimeCubed commented on src/Features/Features.cs
> +        // This ideally should be able to support an arbitrary amount of outros for alternate endings. Personally I'd also be fine with only allowing two, one being `outro_scene_alt`, seems like a re
Any slideshow in the `slugbase\slideshows` should be automatically loaded, meaning this feature isn't actually that important; it serves no purpose except indicating which one should be used as the default outro scene.
I think this should be renamed to `"outro_slideshow"` and accept a single slideshow ID. If the modder wants to add alternate endings, they will need to write C# anyways and should add their own feature.

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/AssetHooks.cs
> +            CustomScene.QueueDream("");
What if the player dies but is revived, a player in coop dies, or a slugpup dies?

2023-07-16 08:14 UTC, SlimeCubed commented on src/Assets/AssetHooks.cs
> +            CustomScene.QueueDream("");
What if a mod causes the game to exit to a process other than the main menu?

2023-08-06 20:36 UTC, SlimeCubed approved these changes

2023-08-06 22:14 UTC, merged